# version: '3.8'
# services:
#   auth: 
#     build: 
#       context: ./apps/auth
#     ports:
#       -3001:3001
#   grpc:
#     build: 
#       context: ./apps/grpc
#     ports:
#       -3002:3002
#   orders:
#     build: 
#       context: ./apps/orders
#     ports:
#       -3003:3003
#   wallet:
#     build: 
#       context: ./apps/wallet
#     ports:
#       -3003:3003